-- 1. 외래키 제약조건 비활성화 및 기존 테이블 삭제
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CHECKLIST;
DROP TABLE IF EXISTS BOARD_LIKE;
DROP TABLE IF EXISTS BOARD_COMMENT;
DROP TABLE IF EXISTS BOARD_REPLY;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS MEMBER;

SET FOREIGN_KEY_CHECKS = 1;

-- 2. 회원 테이블 (MEMBER)
CREATE TABLE MEMBER (
    id VARCHAR(50) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    auth_status VARCHAR(20) DEFAULT 'Y',
    role VARCHAR(20) DEFAULT 'USER',
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. 통합 게시판 테이블 (BOARD)
CREATE TABLE BOARD (
    num INT AUTO_INCREMENT PRIMARY KEY,
    writer VARCHAR(50),
    writer_id VARCHAR(50) DEFAULT NULL,
    writer_nickname VARCHAR(50) DEFAULT NULL,
    board_type VARCHAR(20) DEFAULT 'FREE',
    category VARCHAR(50) DEFAULT 'FREE',
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    readcount INT DEFAULT 0,
    like_count INT DEFAULT 0,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_board_writer FOREIGN KEY (writer_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

-- 4. 게시글 댓글 테이블 (BOARD_COMMENT)
CREATE TABLE BOARD_COMMENT (
    comment_num INT AUTO_INCREMENT PRIMARY KEY,
    board_num INT NOT NULL,
    writer VARCHAR(50),
    writer_id VARCHAR(50),
    writer_nickname VARCHAR(50),
    content TEXT NOT NULL,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_board FOREIGN KEY (board_num) REFERENCES BOARD(num) ON DELETE CASCADE,
    CONSTRAINT fk_comment_writer FOREIGN KEY (writer_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

-- 5. 게시글 추천 테이블 (BOARD_LIKE)
CREATE TABLE BOARD_LIKE (
    board_num INT NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (board_num, user_id),
    CONSTRAINT fk_like_board FOREIGN KEY (board_num) REFERENCES BOARD(num) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);
-- 5-1. 게시글 첨부파일 테이블 (BOARD_FILE) - 사진/동영상 첨부
CREATE TABLE BOARD_FILE (
    file_num INT AUTO_INCREMENT PRIMARY KEY,
    board_num INT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    saved_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL,      -- IMAGE / VIDEO
    file_size BIGINT DEFAULT 0,
    upload_order INT DEFAULT 0,          -- 본문 내 [img1]/[video1] 매칭 순서
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_boardfile_board FOREIGN KEY (board_num) REFERENCES BOARD(num) ON DELETE CASCADE
);
 
-- 6. 체크리스트 테이블 (CHECKLIST)
CREATE TABLE CHECKLIST (
    check_id INT AUTO_INCREMENT PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    content VARCHAR(300) NOT NULL,
    is_completed CHAR(1) DEFAULT 'N',
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_member FOREIGN KEY (member_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

CREATE TABLE VISIT_LOG (
    visit_date DATE NOT NULL,
    session_id VARCHAR(100) NOT NULL,
    first_visit_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (visit_date, session_id)
);

--계정별 체크리스트 상태 
 CREATE TABLE USER_CHECKLIST (
     USER_ID       VARCHAR(50)   PRIMARY KEY,
     CHECKED_KEYS  VARCHAR(1000),
     CHECKED_CNT   INT           DEFAULT 0,
     TOTAL_CNT     INT           DEFAULT 0,
     UPDATED_AT    DATETIME      DEFAULT CURRENT_TIMESTAMP
 );
 ALTER TABLE USER_CHECKLIST ADD CONSTRAINT FK_CHECKLIST_MEMBER
     FOREIGN KEY (USER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE;

-- 관리자 계정 새로 생성
INSERT INTO MEMBER (id, password, name, nickname, email, auth_status, role)
VALUES ('admin', 'admin1234', '관리자', '관리자', 'admin@example.com', 'Y', 'ADMIN');


