-- 1. 외래키 제약조건 비활성화 및 기존 테이블 삭제
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CHECKLIST;
DROP TABLE IF EXISTS BOARD_LIKE;
DROP TABLE IF EXISTS BOARD_COMMENT;
DROP TABLE IF EXISTS BOARD_REPLY;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS MEMBER;

SET FOREIGN_KEY_CHECKS = 1;

-- 2. 회원 테이블 (MEMBER)
CREATE TABLE MEMBER (
    id VARCHAR(50) PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    auth_status VARCHAR(20) DEFAULT 'Y',
    role VARCHAR(20) DEFAULT 'USER',
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. 통합 게시판 테이블 (BOARD)
CREATE TABLE BOARD (
    num INT AUTO_INCREMENT PRIMARY KEY,
    writer VARCHAR(50),
    writer_id VARCHAR(50) DEFAULT NULL,
    writer_nickname VARCHAR(50) DEFAULT NULL,
    board_type VARCHAR(20) DEFAULT 'FREE',
    category VARCHAR(50) DEFAULT 'FREE',
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    readcount INT DEFAULT 0,
    like_count INT DEFAULT 0,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_board_writer FOREIGN KEY (writer_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

-- 4. 게시글 댓글 테이블 (BOARD_COMMENT)
CREATE TABLE BOARD_COMMENT (
    comment_num INT AUTO_INCREMENT PRIMARY KEY,
    board_num INT NOT NULL,
    writer VARCHAR(50),
    writer_id VARCHAR(50),
    writer_nickname VARCHAR(50),
    content TEXT NOT NULL,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_board FOREIGN KEY (board_num) REFERENCES BOARD(num) ON DELETE CASCADE,
    CONSTRAINT fk_comment_writer FOREIGN KEY (writer_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

-- 5. 게시글 추천 테이블 (BOARD_LIKE)
CREATE TABLE BOARD_LIKE (
    board_num INT NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (board_num, user_id),
    CONSTRAINT fk_like_board FOREIGN KEY (board_num) REFERENCES BOARD(num) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);

-- 6. 체크리스트 테이블 (CHECKLIST)
CREATE TABLE CHECKLIST (
    check_id INT AUTO_INCREMENT PRIMARY KEY,
    member_id VARCHAR(50) NOT NULL,
    content VARCHAR(300) NOT NULL,
    is_completed CHAR(1) DEFAULT 'N',
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_member FOREIGN KEY (member_id) REFERENCES MEMBER(id) ON DELETE CASCADE
);
